import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../components/artifact/artifact_data.dart';
import '../components/artifact/artifact_widget.dart';
import '../components/character_portrait/character_portrait_data.dart';
import '../components/weapon/weapon_data.dart';
import '../components/weapon/weapon_widget.dart';
import '../constants/colors.dart';

import '../pages/reusable/artifact_recommend.dart';
import '../pages/reusable/artifact_stat_recommend.dart';
import '../pages/reusable/party_team.dart';
import '../pages/reusable/talent_priority.dart';
import '../pages/reusable/weapon_recommend.dart';
import 'character_model.dart';

var _bodyText1 = TextStyle(
  fontSize: 14.sp,
  fontWeight: FontWeight.w500,
  color: Colors.white,
);

var _bodyText2 = TextStyle(
  fontSize: 13.sp,
  fontWeight: FontWeight.w400,
  color: Colors.white,
);

var albedo = CharacterModel(
  gachaSplashArt: 'albedo_gacha_splash.png',
  gachaSplashCard: 'albedo_gacha_card.png',
  name: 'Albedo',
  element: 'Geo',
  rarity: 5,
  region: 'Mondstadt',
  weaponType: 'Sword',
  role: 'Off-field DPS',
  birthday: 'September 13th',
  description:
      'A genius known as the Kreindeprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knight of Favonius',
  color: geoBG,
  talent1: TalentNormalModel(
    talentImage: 'sword_type.png',
    talentName: 'Normal Attack: Favonius Blackwork - Weiss',
    normalAttackDesc: [
      'Perform up to 5 rapid strikes',
    ],
    chargedlAttackDesc: [
      'Consumes a certain acount of Stamina to unleash 2 rapid sword strikes'
    ],
    plungelAttackDesc: [
      'Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.'
    ],
  ),
  talent2: TalentSkillModel(
    talentImage: 'albedo_elemental_skill.png',
    talentName: 'Abiogenesis: Solar Isotoma',
    description: [
      TalentText(
        talentText:
            'Albedo creates a Solar Isotoma using alchemy, which deals Aoe Geo DMG on apperance',
      ),
      TalentText(
        talentText: 'Solar Isotoma',
        isHighlight: true,
      ),
      TalentText(
        talentText: 'has the following properties:',
      ),
      TalentText(
        talentText:
            "• When opponents within the Solar Isotoma field take DMG, the Solar Isotoma will generate Transient Blossoms which deal AoE Geo DMG. DMG dealt scales off Albedo's DEF.",
      ),
      TalentText(
        talentText:
            'Albedo creates a Solar Isotoma using alchemy, which deals Aoe Geo DMG on apperance',
      ),
      TalentText(
        talentText: '• Transient Blossoms can only be generated once every 2s.',
      ),
      TalentText(
        talentText:
            '• When a character is located at the locus of the Solar Isotoma, the Solar Isotoma will accumulate Geo power to form a crystallized platform that lifts the character up to a certain height. Only one crystallized platform can exist at a time.',
      ),
      TalentText(
        talentText:
            '• Solar Isotoma is considered a Geo ruct. Only one Solar Isotoma created by Albedo himself can exist at a time.',
      ),
    ],
  ),
  talent3: TalentSkillModel(
    talentImage: 'albedo_elemental_burst.png',
    talentName: 'Rite of Progeniture: Tectonic Tide',
    description: [
      TalentText(
        talentText:
            "Under Albedo's command, Geo crystals surge and burst forth, dealing AoE Geo DMG in front of him. If a Solar Isotoma created by Albedo himself is on the field, 7 Fatal Blossoms will be generated in the Solar Isotoma field, bursting violently into bloom and dealing AoE Geo DMG.",
      ),
      TalentText(
        talentText:
            'Tectonic Tide DMG and Fatal Blossom DMG will not generate Transient Blossoms.',
      ),
    ],
  ),
  passive1: PassiveModel(
    talentImage: 'albedo_passive_1.png',
    talentName: 'Calcite Might',
    description: [
      TalentText(
        talentText:
            'Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to opponents whose HP is below 50%.',
      ),
    ],
  ),
  passive2: PassiveModel(
    talentImage: 'albedo_passive_2.png',
    talentName: 'Homuncular Nature',
    description: [
      TalentText(
        talentText:
            'Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.',
      ),
    ],
  ),
  passive3: PassiveModel(
    talentImage: 'albedo_passive_3.png',
    talentName: 'Flash of Genius',
    description: [
      TalentText(
        talentText:
            'When Albedo crafts Weapon Ascension Materials, he has a 10% chance to receive double the product.',
      ),
    ],
  ),
  constellation1: ConstellationModel(
    talentImage: 'albedo_constellation_1.png',
    talentName: 'Flower of Eden',
    description: [
      TalentText(
        talentText:
            "Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.",
      ),
    ],
  ),
  constellation2: ConstellationModel(
    talentImage: 'albedo_constellation_2.png',
    talentName: 'Opening of Phanerozoic',
    description: [
      TalentText(
        talentText:
            'Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s:',
      ),
      TalentText(
        talentText:
            "• Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.",
      ),
      TalentText(
        talentText: '• This effect stacks up to 4 times',
      ),
    ],
  ),
  constellation3: ConstellationModel(
    talentImage: 'albedo_constellation_3.png',
    talentName: 'Grace of Helios',
    description: [
      TalentText(
        talentText:
            'Increases the Level of Abiogenesis: Solar Isotoma by 3. Maximum upgrade level is 15.',
      ),
    ],
  ),
  constellation4: ConstellationModel(
    talentImage: 'albedo_constellation_4.png',
    talentName: 'Descent of Divinity',
    description: [
      TalentText(
        talentText:
            'Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.',
      ),
    ],
  ),
  constellation5: ConstellationModel(
    talentImage: 'albedo_constellation_5.png',
    talentName: 'Tide of Hadean',
    description: [
      TalentText(
        talentText:
            'Increases the Level of Rite of Progeniture: Tectonic Tide by 3. Maximum upgrade level is 15.',
      ),
    ],
  ),
  constellation6: ConstellationModel(
    talentImage: 'albedo_constellation_6.png',
    talentName: 'Dust of Purification',
    description: [
      TalentText(
        talentText:
            'Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.',
      ),
    ],
  ),
  builds: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        "Off-field DPS",
        style: _bodyText1.copyWith(fontSize: 16.sp),
      ),
      const TalentPriority(
        talent1: 'albedo_elemental_skill.png',
        talent2: 'albedo_elemental_burst.png',
        talent3: 'sword_type.png',
        color: geoBG,
      ),
      Text(
        "Weapon",
        style: _bodyText1.copyWith(fontSize: 16.sp),
      ),
      SizedBox(height: 5.h),
      Text(
        "1:2 ratio or 60/120 CRIT RATE/DMG",
        style: _bodyText2.copyWith(fontWeight: FontWeight.w600),
      ),
      WeaponRecommend(
        weaponWidgetList: [
          WeaponWidget(weaponModel: cinnabarSpindle),
          WeaponWidget(weaponModel: primordialJadeCutter),
          WeaponWidget(weaponModel: summitShaper),
          WeaponWidget(weaponModel: harbingerOfDawn),
        ],
      ),
      Text(
        "Artifact",
        style: _bodyText1.copyWith(fontSize: 16.sp),
      ),
      const ArtifactStatRecommend(
        sand: 'DEF%',
        goblet: 'DEF% / Geo DMG Bonus',
        circlet: 'CRIT RATE / CRIT DMG / DEF%',
      ),
      Text(
        "Substat Priority: CRIT > DEF% > DEF",
        style: _bodyText2.copyWith(fontWeight: FontWeight.w600),
      ),
      ArtifactRecommend(
        artifactWidgetList: [
          ArtifactWidget(artifactModel: huskOfOpulentDreams, isFullset: true),
          ArtifactWidget(artifactModel: huskOfOpulentDreams, isFullset: false),
          ArtifactWidget(artifactModel: archaicPetra, isFullset: false),
          ArtifactWidget(artifactModel: noblesseOblige, isFullset: false),
        ],
      ),
    ],
  ),
  teamComposition: Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      Text(
        "Double Geo Team",
        style: _bodyText1.copyWith(fontSize: 16.sp),
      ),
      PartyTeam(
        firstSlot: xiaoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: jeanPortrait,
        fourthSlot: albedoPortrait,
      ),
      PartyTeam(
        firstSlot: hutaoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: xingqiuPortrait,
        fourthSlot: albedoPortrait,
      ),
      SizedBox(height: 10.h),
      Text(
        "Mono Geo Team",
        style: _bodyText1.copyWith(fontSize: 16.sp),
      ),
      PartyTeam(
        firstSlot: ittoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: gorouPortrait,
        fourthSlot: albedoPortrait,
      ),
    ],
  ),
);
