import 'package:flutter/material.dart';

import '../components/artifact/model/artifact_data.dart';
import '../components/artifact/model/artifact_widget.dart';
import '../components/character_portrait/model/character_portrait_data.dart';
import '../components/weapon/model/weapon_data.dart';
import '../components/weapon/model/weapon_widget.dart';
import '../constants/colors.dart';
import '../constants/variables.dart';
import '../pages/reusable/artifact_recommend.dart';
import '../pages/reusable/artifact_stat_recommend.dart';
import '../pages/reusable/party_team.dart';
import '../pages/reusable/talent_image_name.dart';
import '../pages/reusable/talent_priority.dart';
import '../pages/reusable/weapon_recommend.dart';
import 'character_model.dart';

final albedo = CharacterModel(
  gachaSplashArt: 'albedo_gacha_splash.png',
  gachaSplashCard: 'albedo_gacha_card.png',
  name: 'Albedo',
  element: 'Geo',
  rarity: 5,
  region: 'Mondstadt',
  weaponType: 'Sword',
  role: 'Off-field DPS',
  birthday: 'September 13th',
  description:
      'A genius known as the Kreindeprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knight of Favonius',
  talent1: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        isNormalAttack: true,
        image: "sword_type.png",
        name: "Normal Attack: Favonius Blackwork - Weiss",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Normal Attack",
        style: fontStyle1,
      ),
      Text(
        "Perform up to 5 rapid strikes",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Charged Attack",
        style: fontStyle1,
      ),
      Text(
        "Consumes a certain acount of Stamina to unleash 2 rapid sword strikes",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Plunging Attack",
        style: fontStyle1,
      ),
      Text(
        "Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
        style: fontStyle2,
      ),
    ],
  ),
  talent2: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_elemental_skill.png",
        name: "Abiogenesis: Solar Isotoma",
        color: geoBG,
      ),
      Text(
        "Albedo creates a Solar Isotoma using alchemy, which deals Aoe Geo DMG on apperance",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Solar Isotoma",
        style: fontStyle1,
      ),
      Text(
        "has the following properties:",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• When opponents within the Solar Isotoma field take DMG, the Solar Isotoma will generate Transient Blossoms which deal AoE Geo DMG. DMG dealt scales off Albedo's DEF.",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• Transient Blossoms can only be generated once every 2s.",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• When a character is located at the locus of the Solar Isotoma, the Solar Isotoma will accumulate Geo power to form a crystallized platform that lifts the character up to a certain height. Only one crystallized platform can exist at a time.",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• Solar Isotoma is considered a Geo construct. Only one Solar Isotoma created by Albedo himself can exist at a time.",
        style: fontStyle2,
      ),
    ],
  ),
  talent3: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_elemental_burst.png",
        name: "Rite of Progeniture: Tectonic Tide",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Under Albedo's command, Geo crystals surge and burst forth, dealing AoE Geo DMG in front of him. If a Solar Isotoma created by Albedo himself is on the field, 7 Fatal Blossoms will be generated in the Solar Isotoma field, bursting violently into bloom and dealing AoE Geo DMG.",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Tectonic Tide DMG and Fatal Blossom DMG will not generate Transient Blossoms.",
        style: fontStyle2,
      ),
    ],
  ),
  passive1: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_passive_1.png",
        name: "Calcite Might",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to opponents whose HP is below 50%.",
        style: fontStyle2,
      ),
    ],
  ),
  passive2: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_passive_2.png",
        name: "Homuncular Nature",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.",
        style: fontStyle2,
      ),
    ],
  ),
  passive3: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_passive_3.png",
        name: "Flash of Genius",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "When Albedo crafts Weapon Ascension Materials, he has a 10% chance to receive double the product.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation1: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_1.png",
        name: "Flower of Eden",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation2: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_2.png",
        name: "Opening of Phanerozoic",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s:",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.",
        style: fontStyle2,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "• This effect stacks up to 4 times.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation3: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_3.png",
        name: "Grace of Helios",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Increases the Level of Abiogenesis: Solar Isotoma by 3. Maximum upgrade level is 15.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation4: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_4.png",
        name: "Descent of Divinity",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation5: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_5.png",
        name: "Tide of Hadean",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Increases the Level of Rite of Progeniture: Tectonic Tide by 3. Maximum upgrade level is 15.",
        style: fontStyle2,
      ),
    ],
  ),
  constellation6: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const TalentImageName(
        image: "albedo_constellation_6.png",
        name: "Dust of Purification",
        color: geoBG,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.",
        style: fontStyle2,
      ),
    ],
  ),
  builds: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        "Off-field DPS",
        style: fontStyle3,
      ),
      const TalentPriority(
        talent1: 'albedo_elemental_skill.png',
        talent2: 'albedo_elemental_burst.png',
        talent3: 'sword_type.png',
        color: geoBG,
      ),
      Text(
        "Weapon",
        style: fontStyle3,
      ),
      const SizedBox(height: mainPadding),
      Text(
        "1:2 ratio or 60/120 CRIT RATE/DMG",
        style: fontStyle2,
      ),
      WeaponRecommend(
        weaponWidgetList: [
          WeaponWidget(weaponModel: cinnabarSpindle),
          WeaponWidget(weaponModel: primordialJadeCutter),
          WeaponWidget(weaponModel: summitShaper),
          WeaponWidget(weaponModel: harbingerOfDawn),
        ],
      ),
      Text(
        "Artifact",
        style: fontStyle3,
      ),
      const ArtifactStatRecommend(
        sand: 'DEF%',
        goblet: 'DEF% / Geo DMG Bonus',
        circlet: 'CRIT RATE / CRIT DMG / DEF%',
      ),
      Text(
        "Substat Priority: CRIT > DEF% > DEF",
        style: fontStyle2,
      ),
      ArtifactRecommend(
        artifactWidgetList: [
          ArtifactWidget(artifactModel: huskOfOpulentDreams, isFullset: true),
          ArtifactWidget(artifactModel: huskOfOpulentDreams, isFullset: false),
          ArtifactWidget(artifactModel: archaicPetra, isFullset: false),
          ArtifactWidget(artifactModel: noblesseOblige, isFullset: false),
        ],
      ),
    ],
  ),
  teamComposition: Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      Text(
        "Double Geo Team",
        style: fontStyle3,
      ),
      PartyTeam(
        firstSlot: xiaoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: jeanPortrait,
        fourthSlot: albedoPortrait,
      ),
      PartyTeam(
        firstSlot: hutaoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: xingqiuPortrait,
        fourthSlot: albedoPortrait,
      ),
      const SizedBox(height: secondaryPadding),
      Text(
        "Mono Geo Team",
        style: fontStyle3,
      ),
      PartyTeam(
        firstSlot: ittoPortrait,
        secondSlot: zhongliPortrait,
        thirdSlot: gorouPortrait,
        fourthSlot: albedoPortrait,
      ),
    ],
  ),
);
